apiVersion: v1
kind: Service
metadata:
  name: dispatch-service
  namespace: helep
  labels:
    app: dispatch-service
    app.kubernetes.io/part-of: helep
spec:
  selector:
    app: dispatch-service
  ports:
    - name: http
      port: 8003
      targetPort: 8003
      protocol: TCP
  type: ClusterIP
