apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-service-data
  namespace: helep
  labels:
    app: notification-service
    app.kubernetes.io/part-of: helep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
