apiVersion: v1
kind: Service
metadata:
  name: sos-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: sos-service
    app.kubernetes.io/part-of: helep
spec:
  selector:
    app: sos-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  type: ClusterIP
