apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sos-service-netpol
  namespace: helep
  labels:
    app: sos-service
    app.kubernetes.io/part-of: helep
spec:
  podSelector:
    matchLabels:
      app: sos-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: helep
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - port: 8002
          protocol: TCP
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - port: 8002
          protocol: TCP
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: helep
      ports:
        - port: 9092
          protocol: TCP
    - to: []
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
