apiVersion: v1
kind: Service
metadata:
  name: sos-service
  namespace: helep
  labels:
    app: sos-service
    app.kubernetes.io/part-of: helep
spec:
  selector:
    app: sos-service
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      protocol: TCP
  type: ClusterIP
