apiVersion: v1
kind: Secret
metadata:
  name: helep-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: helep
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.global.jwtSecret | quote }}
