apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-service-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: notification-service
    app.kubernetes.io/part-of: helep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
